import Navbar from '@/components/common/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter,Playfair_Display,Montserrat } from 'next/font/google'
import StoreProvider from './StoreProvider'

const inter = Inter({ subsets: ['latin'] })
const MontserratFont = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${MontserratFont.className} px-[140px] pt-11`}>
        <StoreProvider>
        {children}
        </StoreProvider>
        </body>
    </html>
  )
}
